### ISSUE TITLE
Tailwind JIT not adding new classes

### ISSUE THREAD

**Issue by davenathanael** [c4710n/PETAL-starter#1]
Hi, great project and really helpful assets default people can use, huge thanks for that!

I'm new to Phoenix and been trying to use your assets folder to an existing Phoenix project I bootstrapped from fullstackphoenix.com. I followed the instruction on removing my whole /assets directory and downloading yours, replacing the old one. Then I just npm install, run, added some tw classes (i.e. `bg-gray-200`). Apparently after the auto-restart, or even full app restart, the new class didn't got compiled to the main css.

Is there any further configuration I need to do or specific thing with this mechanism I need to check further?
Thanks for your time! :D

**Comment by c4710n** [comment]
Maybe you can create a minimal repo for reproducing this issue, and post the repo URL at here.

> It's hard to address problems without code.

**Comment by davenathanael** [comment]
Hello, sorry yup should have done that before.

Minimal project: https://github.com/davenathanael/PETAL-minimal
Here's a new project I made with `mix phx.new --no-ecto --live`
1. New project, get dependencies
2. Remove `./assets`
3. Replace with this project's `/assets`
4. `npm i` on `./assets`
5. `mix phx.server`
6. Add `text-2xl` and `bg-red-200` on `lib/demo_web/live/page_live.html.leex` `<p class="text-2xl bg-red-200">Peace of mind from prototype to production</p>`
7. `text-2xl` style applied but `bg-red-200` not, its not on the compiled css as well

Environment:
Ubuntu WSL2 on Windows 10
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Mix 1.12.0 (compiled with Erlang/OTP 24)

**Comment by c4710n** [comment]
Thanks for your detailed instructions. I have addressed the problem.


This project has an overrided color palette:
https://github.com/c4710n/PETAL-starter/blob/b68723d850a16758c28ecc369198ac874ca76438/apps/hello_web/assets/tailwind.config.js#L19

It let you use colors like `bg-primary-200` / `bg-info-500` which is more meaningful than default color names.

**If you don't want it, just remove the `colors` object in `tailwind.config.js`. Then, the deafult color names will be available to you.**

**Comment by c4710n** [comment]
If this solve your problem, please consider to close this issue.

**Comment by davenathanael** [comment]
Hello, sorry for the super late response 😅 

Thanks for your assistance, much appreciated! I didn't realize that it was overridden instead of extended. That is surely helpful and a good default. But for my use, I'll move the additional colors to `extend` part of the tailwind config so I can use both.

Thank you, closing this issue 😀

**Comment by c4710n** [comment]
I will use `extend`, too. ;)
